[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remappings
remappings = [
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v2-core/=lib/v2-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/v2-periphery/=lib/v2-periphery/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
